baseURL = 'https://michaelmuratov.com'
languageCode = 'en-us'
title = 'Michael Muratov'
theme='hugo-simple'
enableRobotsTXT = true

[outputs]
home = ['HTML', 'RSS', 'JSON']
section = ['HTML', 'RSS', 'JSON']
taxonomy = ['HTML', 'RSS']

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  defaultMarkdownHandler = 'goldmark' 
  _merge = 'deep'
  
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 3

  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      guessSyntax = "true"
      codeFences = "true"
      lineNos = true
      lineNumbersInTable = false
      noClasses = true

      #style = "monokai"
      style = "catppuccin-mocha"
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
    description = "Personal log for writing and development"
    canonicalBaseURL = "https://michaelmuratov.com"
    [[params.social]]
      name = "LinkedIn"
      url = "https://www.linkedin.com/in/michaelmuratov/"
      icon = "linkedin"
    [[params.social]]
      name = "X"
      url = "https://x.com/MichaelMuratov"
      icon = "x"
    [assets]
        disableHLJS = true
    math = true

# required
[build]
  _merge = 'deep'

# for better seo
[minify]
  _merge = 'deep'

[sitemap]
  changeFreq = 'monthly'


[related]
  includeNewer = true
  threshold = 20
  toLower = false
  [[related.indices]]
    applyFilter = true
    name = 'tags'
    weight = 80
  [[related.indices]]
    applyFilter = true
    name = 'series'
    weight = 120
