baseURL = 'https://michaelmuratov.com'
languageCode = 'en-us'
title = 'Michael Muratov'
theme='hugo-simple'
enableRobotsTXT = true

[markup]
  defaultMarkdownHandler = 'goldmark' 
  _merge = 'deep'
  
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 3

  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      guessSyntax = "true"
      codeFences = "true"
      lineNos = true
      lineNumbersInTable = false
      noClasses = true

      #style = "monokai"
      style = "catppuccin-mocha"
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
    [assets]
        disableHLJS = true
    math = true

# required
[build]
  _merge = 'deep'

# for better seo
[minify]
  _merge = 'deep'

[sitemap]
  changeFreq = 'monthly'


[related]
  includeNewer = true
  threshold = 20
  toLower = false
  [[related.indices]]
    applyFilter = true
    name = 'tags'
    weight = 80
