baseURL = 'https://michaelmuratov.com'
languageCode = 'en-us'
title = 'Michael Muratov'
theme='muratov'
enableRobotsTXT = true
enableGitInfo = true

[outputs]
home = ['HTML', 'RSS', 'JSON', 'STATUS']
section = ['HTML', 'RSS', 'JSON']
taxonomy = ['HTML', 'RSS']

[outputFormats.STATUS]
mediaType = "application/json"
baseName = "status"
isPlainText = true
notAlternative = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[markup]
  defaultMarkdownHandler = 'goldmark' 
  _merge = 'deep'
  
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 3

  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      guessSyntax = "true"
      codeFences = "true"
      lineNos = true
      lineNumbersInTable = false
      noClasses = true

      #style = "monokai"
      style = "catppuccin-mocha"
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
    description = "Personal log for writing and development"
    canonicalBaseURL = "https://michaelmuratov.com"
    [params.comments]
      enabled = true
      provider = "giscus"
      repo = "muratovm/blog"
      repoId = "R_kgDOOc35og"
      category = "General"
      categoryId = "DIC_kwDOOc35os4C2J3Z"
      mapping = "pathname"
      strict = "0"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "top"
      theme = "light"
      lang = "en"
      loading = "lazy"
    [[params.social]]
      name = "LinkedIn"
      url = "https://www.linkedin.com/in/michaelmuratov/"
      icon = "linkedin"
    [[params.social]]
      name = "X"
      url = "https://x.com/MichaelMuratov"
      icon = "x"
    [[params.social]]
      name = "GitHub"
      url = "https://github.com/muratovm"
      icon = "github"
    [assets]
        disableHLJS = true
    math = true

# required
[build]
  _merge = 'deep'

# for better seo
[minify]
  _merge = 'deep'

[sitemap]
  changeFreq = 'monthly'


[related]
  includeNewer = true
  threshold = 20
  toLower = false
  [[related.indices]]
    applyFilter = true
    name = 'tags'
    weight = 80
  [[related.indices]]
    applyFilter = true
    name = 'series'
    weight = 120
