title = "Website Name"
baseURL = 'https://michaelmuratov.com'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = ""
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true

